version: '3'

services: 
  web:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:8080"
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build: .
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["yarn", "test"]